export const EnumMaps = {
  payment_methods: {
    'Rebate (post purchase)': 'rebate',
    'Point of sale rebate': 'pos_rebate',
    'Account credit': 'account_credit',
    'Tax Credit': 'tax_credit',
    'Assistance program': 'assistance_program',
    Bonus: 'other',
    Multiple: 'other',
    Other: 'other',
    Unknown: 'other',
    Financing: 'other',
  },
  type: {
    'Rebate (post purchase)': 'rebate',
    'Point of sale rebate': 'pos_rebate',
    'Account credit': 'account_credit',
    'Tax Credit': 'tax_credit',
    'Assistance program': 'assistance_program',
    Bonus: 'other',
    Multiple: 'other',
    Other: 'other',
    Unknown: 'other',
    Financing: 'other',
  },
  item_type: {
    'Rebate (post purchase)': 'rebate',
    'Point of sale rebate': 'pos_rebate',
    'Account credit': 'account_credit',
    'Tax Credit': 'tax_credit',
    'Assistance program': 'assistance_program',
    Bonus: 'other',
    Multiple: 'other',
    Other: 'other',
    Unknown: 'other',
    Financing: 'other',
  },
  item: {
    'Ground Source Heat Pump (GSHP) / Geothermal HP':
      'geothermal_heating_installation',
    'HVAC - Air Source Heat Pump': 'heat_pump_air_conditioner_heater',
    'HVAC - Air to Water Heat Pump': 'heat_pump_air_conditioner_heater',
    'HVAC - Ducted Heat Pump': 'heat_pump_air_conditioner_heater',
    'HVAC - Ductless Heat Pump': 'heat_pump_air_conditioner_heater',
    'Heat Pump Water Heater (HPWH)': 'heat_pump_water_heater',
    'New Electric Vehicle': 'new_electric_vehicle',
    'Used Electric Vehicle': 'used_electric_vehicle',
    'Electric Vehicle Charger': 'electric_vehicle_charger',
    'Rooftop Solar': 'rooftop_solar_installation',
    'Battery Storage': 'battery_storage_installation',
    'Heat Pump Dryers / Clothes Dryer': 'heat_pump_clothes_dryer',
    'Electric Stove': 'electric_stove',
    'Weatherization (insulation and air sealing)': 'weatherization',
    'Electric wiring': 'weatherization',
    'Electric panel': 'electric_panel',
    'Electric lawn equipment (mower, edger, leaf blower, weedwhacker)': 'electric_outdoor_equipment',
    'Smart Thermostat': 'smart_thermostat',
    'E-Bike': 'ebike',
    'Induction Cooktop': 'electric_stove',
    Other: 'other',
  },
  amount_type: {
    'dollar per unit': 'dollars_per_unit',
    'percent with a cap': 'percent',
    'dollar amount with a cap': 'dollar_amount',
  },
  authority_type: {
    Local: 'local',
  },
};
