name: Incentives Freshness Check
on:
  schedule:
    - cron: '30 5 * * 1'
permissions:
  contents: read
jobs:
  verify-incentives-freshness:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v5
        with:
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
          node-version: 22.x
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn build
      - name: URL checker
        run: yarn check-data-freshness
